id: P3D04BD4D
initial_creation_type: ocr
source_metadata:
  volumes:
    74e8108ce6614f05ac5780f99f59695b:
      base_file: v034.txt
      image_group_id: I1PD95879
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་སྙིང་པོའི་སྒྲུབ་ཐབས།
      total_pages: 1734
      volume_number: 34
